### ISSUE TITLE
Swap to ratatui

### ISSUE THREAD

**Issue by auronandace** [funbiscuit/spacedisplay-rs#4]
Just wanted to make you aware that the tui crate is not being maintained any more. The following is a fork that is now actively developed:

https://github.com/tui-rs-revival/ratatui

I hope this will be of benefit to your project.

**Comment by funbiscuit** [comment]
Thanks for the reminder! I'll switch to it in the near future, didn't know that fork existed (didn't check `tui-rs` status for several months).
